# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    dag.controller.configuration_factory.class: DAG\Bundle\ResourceBundle\Controller\ConfigurationFactory
    dag.controller.parameters_parser.class: DAG\Bundle\ResourceBundle\Controller\ParametersParser
    dag.expression_language.class: DAG\Bundle\ResourceBundle\ExpressionLanguage\ExpressionLanguage
    dag.form.type.object_to_identifier.class: DAG\Bundle\ResourceBundle\Form\Type\ObjectToIdentifierType
    dag.event_subscriber.load_orm_metadata.class: DAG\Bundle\ResourceBundle\EventListener\LoadORMMetadataSubscriber
    dag.event_subscriber.kernel_controller.class: DAG\Bundle\ResourceBundle\EventListener\KernelControllerSubscriber
    jms_serializer.identifier_handler.class: DAG\Bundle\ResourceBundle\Serializer\IdentifierHandler
    jms_serializer.property_handler.class: DAG\Bundle\ResourceBundle\Serializer\PropertyHandler
    dag.expression_language.extension.resource.class: DAG\Bundle\ResourceBundle\ExpressionLanguage\ResourceExtension

services:
    dag.expression_language.extension.resource:
        class: %dag.expression_language.extension.resource.class%
        tags: [{ name: dag.expression_language_extension }]

    dag.controller.configuration_factory:
        class: %dag.controller.configuration_factory.class%
        arguments: ["@dag.controller.parameters_parser"]

    dag.controller.parameters_parser:
        class: %dag.controller.parameters_parser.class%
        arguments: ["@dag.expression_language"]

    dag.expression_language:
        class: %dag.expression_language.class%
        calls: [["setContainer", ["@service_container"]]]

    dag.event_subscriber.load_orm_metadata:
        class: %dag.event_subscriber.load_orm_metadata.class%
        arguments: ["%dag.config.classes%", "%dag.config.inheritance%"]
        tags: [{ name: doctrine.event_subscriber }]

    dag.event_subscriber.kernel_controller:
        class: %dag.event_subscriber.kernel_controller.class%
        arguments: ["@security.authorization_checker", "@dag.expression_language"]
        tags: [{ name: kernel.event_subscriber }]

    dag.form.type.object_to_identifier:
        class: %dag.form.type.object_to_identifier.class%
        abstract: true

    jms_serializer.identifier_handler:
        class: %jms_serializer.identifier_handler.class%
        tags: [{ name: jms_serializer.subscribing_handler }]

    jms_serializer.property_handler:
        class: %jms_serializer.property_handler.class%
        tags: [{ name: jms_serializer.subscribing_handler }]
