# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.twig.extension.resource.class: DAG\Bundle\ResourceBundle\Twig\ResourceExtension
    dag.twig.extension.resource.pagination_template: 'DAGResourceBundle:Twig:paginate.html.twig'
    dag.twig.extension.resource.sorting_template: 'DAGResourceBundle:Twig:sorting.html.twig'

services:

    dag.twig.extension.resource:
        class: %dag.twig.extension.resource.class%
        arguments:
            - @router
            - %dag.twig.extension.resource.pagination_template%
            - %dag.twig.extension.resource.sorting_template%
        tags:
            - { name: twig.extension }
            - { name: kernel.event_listener, event: kernel.request, method: fetchRequest }
