# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.event_subscriber.field.load_orm_metadata.class: DAG\Bundle\FieldBundle\EventListener\LoadORMMetadataSubscriber

services:

    dag.event_subscriber.field.load_orm_metadata:
        class: %dag.event_subscriber.field.load_orm_metadata.class%
        arguments: ["%dag.field.subjects%"]
        tags:
            - { name: doctrine.event_subscriber }
