# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Field\Model\Field:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: "name", message: dag.field.name.unique, groups: ['dag'] }
    properties:
        name:
            - NotBlank: { message: dag.field.name.not_blank, groups: ['dag'] }
            - Regex: { pattern: "/^[a-z0-9-]+$/", message: dag.field.name.slug, groups: ['dag'] }
            - Length: { min: 3, max: 120, minMessage: dag.field.name.length.min, maxMessage: dag.field.name.length.max, groups: ['dag'] }
        presentation:
            - NotBlank: { message: dag.field.presentation.not_blank, groups: ['dag'] }
            - Length: { min: 3, max: 120, minMessage: dag.field.presentation.length.min, maxMessage: dag.field.presentation.length.max, groups: ['dag'] }
        type:
            - NotBlank: { message: dag.field.type.not_blank, groups: ['dag'] }
            - Choice: { callback: ['DAG\Component\Field\Model\FieldTypes', 'getKeys'], strict: true, message: dag.field.type.choice, groups: ['dag'] }
        option:
            - Type: { type: DAG\Component\Option\Model\OptionInterface, message: dag.field.option.type, groups: ['dag'] }
        allowMultiple:
            - Type: { type: bool, message: dag.field.option.type, groups: ['dag'] }

DAG\Component\Field\Model\FieldValue: 
    properties:
        subject:
            - NotBlank: { message: dag.field_value.subject.not_blank, groups: ['dag'] }
            - Type: { type: DAG\Component\Field\Model\FieldSubjectInterface, message: dag.field_value.subject.type, groups: ['dag'] }
        field:
            - NotBlank: { message: dag.field_value.field.not_blank, groups: ['dag'] }
            - Type: { type: DAG\Component\Field\Model\FieldInterface, message: dag.field_value.field.type, groups: ['dag'] }
