# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.controller.settings.class: DAG\Bundle\SettingsBundle\Controller\SettingsController
    dag.settings.form_factory.class: DAG\Bundle\SettingsBundle\Form\Factory\SettingsFormFactory
    dag.settings.manager.class: DAG\Bundle\SettingsBundle\Manager\SettingsManager
    dag.settings.schema_registry.class: DAG\Bundle\SettingsBundle\Schema\SchemaRegistry

services:

    dag.controller.settings:
        class: %dag.controller.settings.class%
        calls:
            - ['setContainer', ['@service_container']]

    dag.settings.form_factory:
        class: %dag.settings.form_factory.class%
        arguments: ['@dag.settings.schema_registry', '@form.factory']

    dag.settings.cache:
        alias: doctrine_cache.providers.dag_settings

    dag.settings.manager:
        class: %dag.settings.manager.class%
        arguments:
            - '@dag.settings.schema_registry'
            - '@dag.manager.parameter'
            - '@dag.repository.parameter'
            - '@dag.settings.cache'
            - '@validator'

    dag.settings.schema_registry:
        class: %dag.settings.schema_registry.class%
        arguments: ['@service_container']