# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.templating.helper.settings.class: DAG\Bundle\SettingsBundle\Templating\Helper\SettingsHelper

services:

    dag.templating.helper.settings:
        class: %dag.templating.helper.settings.class%
        arguments: ['@dag.settings.manager']
        tags:
            - { name: templating.helper, alias: dag_settings }