# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.twig.extension.settings.class: DAG\Bundle\SettingsBundle\Twig\SettingsExtension

services:

    dag.twig.extension.settings:
        class: %dag.twig.extension.settings.class%
        arguments: ['@dag.templating.helper.settings']
        tags:
            - { name: twig.extension }
