# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Bundle\SettingsBundle\Model\Parameter:
    properties:
        namespace:
            - NotBlank:
                message: dag.settings.parameter.namespace.not_blank
            - Length:
                min: 1
                minMessage: dag.settings.parameter.namespace.min_length
                max: 120
                maxMessage: dag.settings.parameter.namespace.max_length
        name:
            - NotBlank:
                message: dag.settings.parameter.name.not_blank
            - Length:
                min: 1
                minMessage: dag.settings.parameter.name.min_length
                max: 120
                maxMessage: dag.settings.parameter.name.max_length
