# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Field\Model\FieldValue:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        stringValue:
            type: string
            nullable: true
        dateValue:
            type: datetime
            nullable: true
        numberValue:
            type: integer
            nullable: true

    manyToOne:
        optionValue:
            targetEntity: DAG\Component\Option\Model\OptionValueInterface
            joinColumn:
                name: optionValueId
                nullable: true

    manyToMany:
        optionValues:
            targetEntity: DAG\Component\Option\Model\OptionValueInterface
            joinTable:
                name: accard_%s_field_option_map
                joinColumns:
                    optionValueId:
                        name: optionValueId
                        referencedColumnName: id
                inverseJoinColumns:
                    fieldValueId:
                        name: fieldValueId
                        referencedColumnName: id