# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Field\Model\Field:
    type: mappedSuperclass
    repositoryClass: DAG\Bundle\FieldBundle\Doctrine\ORM\FieldRepository 

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 120
            nullable: false
            unique: true
        presentation:
            type: string
            length: 120
            nullable: false
        type:
            type: string
            length: 36
            nullable: false
        allowMultiple:
            type: boolean
            nullable: false
        addable:
            type: boolean
            nullable: false
            options:
                default: false
        order:
            type: string
            length: 60
            nullable: false
            column: ordering
            options:
                default: "numeric"
        configuration:
            type: array

    manyToOne:
        option:
            targetEntity: DAG\Component\Option\Model\OptionInterface
            cascade: ["persist"]
            joinColumn:
                name: optionId
