# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.event_subscriber.prototype.load_orm_metadata.class: DAG\Bundle\PrototypeBundle\EventListener\LoadORMMetadataSubscriber
    dag.repository.prototype.class: DAG\Bundle\PrototypeBundle\Doctrine\ORM\PrototypeRepository

services:

    dag.event_subscriber.prototype.load_orm_metadata:
        class: %dag.event_subscriber.prototype.load_orm_metadata.class%
        arguments: ["%dag.prototype.subjects%"]
        tags:
            - { name: doctrine.event_subscriber }

    dag.repository.prototype:
        class: %dag.repository.prototype.class%
        factory_service: doctrine
        factory_method: getRepository
        arguments:
             - DAG\Component\Prototype\Model\Prototype
