# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.provider.option.class: DAG\Bundle\OptionBundle\Provider\OptionProvider
    dag.form.type.option_choice.class: DAG\Bundle\OptionBundle\Form\Type\OptionChoiceType
    dag.form.type.option_order_choice.class: DAG\Bundle\OptionBundle\Form\Type\OptionOrderChoiceType

services:

    dag.provider.option:
        class: %dag.provider.option.class%
        arguments:
            - @dag.repository.option

    dag.form.type.option:
        class: %dag.form.type.option.class%
        arguments:
            - %dag.model.option.class%
            - %dag.validation_group.option%
        tags:
            - { name: form.type, alias: dag_option }

    dag.form.type.option_value:
        class: %dag.form.type.option_value.class%
        arguments:
            - %dag.model.option_value.class%
            - %dag.validation_group.option_value%
        tags:
            - { name: form.type, alias: dag_option_value }

    dag.form.type.option_choice:
        class: %dag.form.type.option_choice.class%
        arguments:
            - %dag.model.option.class%
        tags:
            - { name: form.type, alias: dag_option_choice }

    dag.form.type.option_order_choice:
        class: %dag.form.type.option_order_choice.class%
        tags:
            - { name: form.type, alias: dag_option_order_choice }