# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.templating.helper.option.class: DAG\Bundle\OptionBundle\Templating\Helper\OptionHelper

services:

    dag.templating.helper.option:
        class: %dag.templating.helper.option.class%
        arguments: ['@dag.provider.option']
        tags:
            - { name: templating.helper, alias: dag_option }