# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    dag.twig.extension.option.class: DAG\Bundle\OptionBundle\Twig\OptionExtension

services:

    dag.twig.extension.option:
        class: %dag.twig.extension.option.class%
        arguments: ['@dag.templating.helper.option']
        tags:
            - { name: twig.extension }
