# This file is part of The DAG Framework package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DAG\Component\Option\Model\Option: 
    properties: {}

DAG\Component\Option\Model\OptionValue:
    properties:
        value:
            - NotBlank: { message: dag.option.not_blank, groups: ['dag']}
